### ISSUE TITLE
Mosaic and datasrc

### ISSUE THREAD

**Issue by pllim** [ejeschke/ginga#114]
Is it feasible for `datasrc` to permanently cache mosaicked array(s) generated by `Mosaic` until user explicitly deletes the mosaic? I know it can take up lots of memory, but once it is out of the cache, it cannot be automatically regenerated behind the scenes when user clicks on it in `Contents`.

**Comment by ejeschke** [comment]
Actually, it can be recreated (at least it can in many cases)--we are doing that here at Subaru with our customized subclass.  But this is from a known number of frames with always the same parameters.  It might be more difficult to support with the user changing arbitrary parameters.  Still, something to consider.

In any case, I think it might be reasonable to add a feature to "tag" entries in a `Datasrc` so that they are skipped when considering a candidate for ejection from the store.  What should happen when the `Datasrc` is full?  Not accept any new images until one is deleted?

**Comment by pllim** [comment]
Good question. I am not a GUI design expert, but one of these will work for me (I am also open to suggestions):
1. Not accepting new image, like you said. And gives a warning or error?
2. Prompt user to choose ("I am going to delete mosaic0 (yes/no)"), but popup windows can be annoying.

**Comment by pllim** [comment]
Or maybe just recreate it somehow behind the scenes, perhaps using metadata stored in `Contents`?

**Comment by pllim** [comment]
Or maybe save it to disk somewhere temporary (like you do with `.thumbs`?) and reload when needed?

**Comment by ejeschke** [comment]
Not necessarily a solution here, but if you set the channel data buffer length as described in issue #120 your mosaic will never go out of memory.  I believe you can remove it via the Thumbs plugin with the right-click context menu.

**Comment by pllim** [comment]
>  I believe you can remove it via the Thumbs plugin with the right-click context menu.

This is not possible, as discussed in #101. To re-iterate, mosaic does not show up in `Thumbs`. However, I can remove it with "File -> Remove Image".

**Comment by pllim** [comment]
`numImages=0` works for me. My machine has enough memory to make that work, so I'm closing this.
