### ISSUE TITLE
Pan jumps back to center of image

### ISSUE THREAD

**Issue by pllim** [ejeschke/ginga#140]
I have an image displayed on Ginga. I click on free-panning button (the hand icon) and lock it (the lock icon). I use left click and touch pad to move around the image. I release the button and remove my finger from touch pad. Then I use left click and touch pad again to move it somemore (free-panning is still in locked mode). But now, instead of picking up from where I am, the cursor automatically jumps back to the center of the image. Is this a bug?

**Comment by ejeschke** [comment]
Hi @pllim,
That is the way the "free panning" works.  Basically it uses the boundaries of the window as the boundaries of the image, so that as you move the cursor toward the top right corner of the window (for example), you scroll to reveal the top right corner of the image, at the current zoom level.  Therefore it does not matter where you start panning, but where you end up that matters.

It sounds like you are looking for a version of the other kind of panning ("proportional pan", aka "drag pan") where the amount of pan is *more* than proportionate to the drag distance.  In other words, an exaggerated drag pan.  I think this would simply be a variation on the drag pan with some kind of simple multiplier--not too difficult to implement.

**Comment by ejeschke** [comment]
Are you looking for a faster way to pan when heavily zoomed in?

**Comment by pllim** [comment]
Fast or not is not the issue here. I just don't want the display to automatically jump back to the center. I want it to pick up from where I left the cursor (in a locked mode). Does that make sense? Yes, this becomes important when the image is heavily zoomed in, because when it jumps back, I can't find where I was on the image anymore (usually, I would stop at a point of interest, like a bad pixel).

**Comment by ejeschke** [comment]
Is there a reason the drag pan doesn't work for you then?  I'm trying to understand why you wouldn't use it instead. It's the type of panning most people are used to from ds9.

**Comment by pllim** [comment]
Ah, the "four arrows icon". Yeah, that works. Thanks! I instinctively went to the "hand icon" when I want to drag around on the image. It's a habit I picked up from a different software (could be Photoshop).

**Comment by ejeschke** [comment]
I used the 4 arrow icon because that's what matplotlib uses for the same type of panning, and python users would be familiar with it.  BTW, in that mode, liek matplotlib, right drag zooms the image--you might try it.

Maybe we should think about a different icon for free panning?

**Comment by pllim** [comment]
I don't think updating the icon is necessary now that this is clarified. Thanks!
