### ISSUE TITLE
Zoom/pan to remember setting for each image?

### ISSUE THREAD

**Issue by pllim** [ejeschke/ginga#155]
I have 2 images. The point of interest is at different X and Y positions on each of them. I zoomed in  on it nicely on Image 1. When I switch to Image 2, it remembers the position/zoom for Image 1, so I am looking at nothing. I move the red box on `Info` display to get to the point of interest in Image 2, and now I am looking at nothing in Image 1. Is there a way for the zoom/pan to remember the setting that is not the same for both images? Does this make sense?

Here is my setting for Ginga:
```
Cut New: override
Zoom New: off
Center New: off
```

**Comment by pllim** [comment]
I found out that I can have pan/zoom set differently for each image if they are in different channels. But is that the only solution?

**Comment by ejeschke** [comment]
@pllim, could you try commit 077a86be1346eeefe76fe5825db1894d90534f06?  Activate the `Preferences` for the "Image" channel and go down to the "Remember" section.

I recommend that you save the Preferences, quit Ginga and then start up again in order to have the least mental surprises.

There are some niggles that need to be worked out.  Your thorough testing is appreciated.  I also noticed an occasional issue with the new feature that you get a QPainter error.  If you notice any of these, please try to reproduce it and let me know about it.  Tnx.

**Comment by pllim** [comment]
Something is wrong with "Num Images" setting under `Preferences`. It is repeated twice:

1. At the bottom of "New Images" frame, after "Create thumbnail".
2. Under "General" (expandable by clicking the arrow) by itself, with a non-working "Set" button.

**Comment by ejeschke** [comment]
I've removed the duplicate widget--there now should only be one under "General".

**Comment by pllim** [comment]
The new settings seem to work fine (I only enabled saving scale and pan). Have not encountered `QPainter` error yet, but I will let you know if I do.

As for the "Num Images" layout, the duplicate is gone, but its "Set" button is still non-functional.

**Comment by ejeschke** [comment]
Fixed (I think) in commit 3b3ceadb68c13c3592b25906cbef86e6dd8a1407

**Comment by pllim** [comment]
@ejeschke , thank you. It appears fixed, except for some leftover print functions, which I have replaced in #161.
