### ISSUE TITLE
Pan preferences: selecting wcs and apply pan moves off the image

### ISSUE THREAD

**Issue by hcferguson** [ejeschke/ginga#191]
The following steps under Preferences-Panning results in the Pan position moving off the image:

 1. Set Pan Coord to Data and Center the image.
 2. Set Pan Coord to WCS
 3. Select "Apply Pan"

It behaves this way if I display the coordinates in decimal. If I display in sexagesimal, it seems to work properly.

**Comment by ejeschke** [comment]
Good catch.  This is due to the pan position not being reset when the interpretation (`pan_coord`) is changed from `data` to `wcs`.  However if you were to set a new pan position (say, by centering) the new pan position should be in wcs coords.  I think the sexagesimal setting should have nothing to do with it, unless that is somehow forcing the pan position to be reset.

Probably what needs to happen is that the pan position should be converted from data->wcs (and back) when the user changes the combobox.

**Comment by ejeschke** [comment]
Hmm, testing this more closely, I think I misspoke above, and you are right on the money.  It looks like the conversion is happening, and it's fine if set to sexagesimal and incorrectly converted if directly to degrees.

**Comment by ejeschke** [comment]
@hcferguson, the problem was much simpler than I thought and was simply a failure to handle the case of non-sexagesimal (floating point) wcs coordinates in the handler for "Apply Pan".

This is fixed in commit 10fe0ceb9bb051d0832915b6f21ef6b73d87c43c.  Can you check that it works for you? Tnx.
