### ISSUE TITLE
Consider creating a Debian package

### ISSUE THREAD

**Issue by olebole** [ejeschke/ginga#200]
Hi,

I am writing you on the behalf of the [Debian Astronomy Team](https://lists.debian.org/debian-astro/). We are trying to get all important free astronomy software [packaged for Debian](https://qa.debian.org/developer.php?email=debian-astro-maintainers%40lists.alioth.debian.org) (from where it will migrate to Ubuntu and Mint as well). One important group are python packages, especially Astropy Affiliated Packages. Since Ginga is one of the major packages here, it would be definitely worth to be included.

Ideally, this should be done within the Debian Astronomy Team. It could be packaged by one of the GInga developers, or anyone else can volunteer. As far as I investigated the package, the Debian package creation would be not very difficult, so this can even be a task for a beginner.  We can guide you through the full process, and also finally upload your package to Debian. Please contact me directly, or via the [mailing list](https://lists.debian.org/debian-astro/) if you need further information.

Best regards,
Ole

**Comment by ejeschke** [comment]
Hi @olebole!
I would really like to get ginga into debian.  Since it is a pure python package, it should be be pretty easy.  I don't know the first thing about Debian packaging, so if the D.A.T. would be willing to help I would really appreciate it.  If it helps I could send a list of required and recommended python packages.

**Comment by olebole** [comment]
Hi @ejeschke , for Astropy Affilated Packages I wrote a tutorial how to create a Debian package for them:
* [Preparation](https://wiki.debian.org/DebianAstro/AstropyPackagingTutorial/Preparation)
* [Packaging](https://wiki.debian.org/DebianAstro/AstropyPackagingTutorial/Packaging)
* [Upload and Advanced topics](https://wiki.debian.org/DebianAstro/AstropyPackagingTutorial/Packaging)

For pure Python packages, this is quite straightforward. Usually the main work is to carefully peel out all copyrights, but since you are upstream, you probably know this best :-)

**Comment by ejeschke** [comment]
@olebole, is there an automated system for making releases by the D.A.T.?  I must say that the instructions are somewhat daunting, including signing up for various mailing lists, etc.  Wondering if you have a system for just making affiliated packages into debian releases.

Currently I have BSD for the vast majority of the code, and a couple files are Apache License 2.0.  Is that fine for Debian?

**Comment by olebole** [comment]
There are some automated tools, like [stdeb](https://pypi.python.org/pypi/stdeb) and [pypi2deb](https://github.com/p1otr/pypi2deb). They do some formal translation. However, the major work is anyway to be done manually -- mainly to create `debian/copyright` with all licensing information. BSD + Apache-2 is fine for Debian; however it needs to be [documented en detail there](https://www.debian.org/doc/packaging-manuals/copyright-format/1.0/). Also, there may be patches needed for Debian specifics, and finally one needs to test the package.

What concerns the signup: I would just recommend to subscribe to some mailing lists, since they may provide help in case of difficulties. However, they are open for posting by everyone, so if you prefer you may also just send your question there (if you have one), and read the answer on the [archive](https://lists.debian.org/debian-astro/). This is what I do if I have a very specific problem, for example with a certain architecture.
We may also discuss your problems with packaging in this github issue.

There is just one membership I would ask you to take, and this is on the [debian-astro](https://alioth.debian.org/project/request.php?group_id=100893) membership on alioth (which requires an [account there](https://alioth.debian.org/account/register.php)). This is needed since we do a collaborative maintenance on our astronomy packages, and this gives you access to it.

**Comment by olebole** [comment]
Hi Eric, I just started to do the packaging myself and therefore issued an [ITP bug](https://bugs.debian.org/823598) for Debian. You are welcome to contribute, or even to take over the packaging.
The packaging git repository is [here](https://anonscm.debian.org/cgit/debian-astro/packages/ginga.git).

**Comment by ejeschke** [comment]
Hi Ole, that is most excellent!  I really appreciate it, since I'm not really able to take on that responsibility right now.  We just merged the astropy-helpers template, so hopefully that makes it easy to manage it more or less the same as all the other affiliated packages.

There are a couple of packages that I would like to list as "recommended" to be installed with ginga, because they improve either the capabilities or the performance.  I think there is a way to specify that in the python packaging (setuptools) framework, but is there some recommended other way that these should be specified for debian?

**Comment by olebole** [comment]
Concerning the "recommends", I checked your [documentation](http://ginga.readthedocs.io/en/latest/install.html), and have the [following preliminary dependencies](http://anonscm.debian.org/cgit/debian-astro/packages/ginga.git/tree/debian/control):
```
Package: python-ginga
Depends: fonts-roboto-unhinted,
         ${misc:Depends},
         ${python:Depends}
Recommends: python-astropy | python-astlib,
            python-astropy | python-fitsio,
            python-cairo | python-pyqt4,
            python-gtk2 | python-pyqt4,
            python-magic,
            python-matplotlib,
            python-scipy,
            python-webkit
Suggests: python-pil

Package: python3-ginga
Depends: fonts-roboto-unhinted,
         ${misc:Depends},
         ${python3:Depends}
Recommends: python3-astropy | python3-astlib,
            python3-astropy | python3-fitsio,
            python3-magic,
            python3-matplotlib,
            python3-pyqt4,
            python3-scipy
Suggests: python3-pil

Package: ginga
Depends: python3,
         python3-astropy,
         python3-ginga (= ${binary:Version}),
         python3-pkg-resources,
         python3-qt4,
         ${misc:Depends}
```
`${python-depends}` is mainly `python-numpy`. Packages with "Recommends" are usually installed as well when the package gets installed (however, it is no error when they are not available, and one can remove them without removing the parent package). "Suggests" are optional packages, that may be offered for installation, but not automatically selected.
I am not sure about the order of the GUI packages: for the Python 2 version, I selected in the moment gtk2+cairo as the primary library, but for Python 3 it is Qt4, since gtk2+cairo is not available for Python 3. Any remarks here? Better to go with qt for the Python 2 version as well?
For the executable, the Python 3 package is used -- mainly because Python 3 is the upcoming standard. Is there any serious drawback with this? I have made astropy and qt4 strong dependencies; that is probably OK, right?

Still related to the recommendations: In Debian, we have the possibility to [run CI tests](https://ci.debian.net) whenever one of the dependencies changes. Since ginga has a lot of dependencies, it would be nice to get this checked as much as possible. For the UI, there are still no checks, right? It may be already useful to check whether ginga can be started and plots can be made without exceptions here.

Another, small issue: Is there any paper that should be cited for ginga?
And do you have manpages for the binaries? I can create them myself, but if there is already something, I would take it :-) (We need manpages for every program in Debian).

**Comment by ejeschke** [comment]
There is a distinction that is important, which is that the dependencies for someone who is wanting to develop their own viewer using the basic Ginga widget are much less than someone who wants to run up the reference viewer with all the plugins.  The python `setup.py` file is mainly configured for the former.

For the debian release we definitely should add as "required" most of the packages necessary to run the reference viewer with almost everything necessary for all but the most obscure plugins. Your list is close, I think.  To the recommends, I would add:

`python-pil`
`python-opencv`

For suggests, the following would be a good list:
`ipython`
`python-sphinx`
`python-pytest`
`python-fitsio`
`python-astlib`

Is `kapteyn` available as a debian package?  If so, that would also be a good "suggests"

> I am not sure about the order of the GUI packages: for the Python 2 version, I selected in the moment gtk2+cairo as the primary library, but for Python 3 it is Qt4, since gtk2+cairo is not available for Python 3. Any remarks here? Better to go with qt for the Python 2 version as well?
> For the executable, the Python 3 package is used -- mainly because Python 3 is the upcoming standard. Is there any serious drawback with this? I have made astropy and qt4 strong dependencies; that is probably OK, right?

Regarding backends:
Since Ginga supports several toolkits, but we don't want to list all possible requirements for all toolkits, I think we should pick Qt.  Qt has become the kind of "reference" toolkit for Ginga, so I think I would recommend to go with that, although gtk2/cairo as a backend does work well under Linux and it will be supported going forward (and we are planning to support gtk3 soon, I hope).  For Qt the required's should probably be:
`python-pyqt4`
`python-webkit`

Let me know what you think for specifying recommendations for other backends.  I don't know, maybe `matplotlib` has a pretty similar problem, how do they handle that?  Depending on the backend, we could add

`python-tornado`
`python-gtk2`
`python-cairo`
`python-tkinter`

But it doesn't seem right to add these to recommends.

For `python3-ginga`, we should probably go with Qt 5, unless that is not what most other Qt packages are using these days.

> Still related to the recommendations: In Debian, we have the possibility to run CI tests whenever one of the dependencies changes. Since ginga has a lot of dependencies, it would be nice to get this checked as much as possible. For the UI, there are still no checks, right? It may be already useful to check whether ginga can be started and plots can be made without exceptions here.

We could definitely create some tests that produce PNG or PDF plots and check those. What do you think?  To my mind, that is the way ginga works--it creates RGB images that are updated in a widget, so you are actually checking most of the important functionality by producing a screenshot.

> Another, small issue: Is there any paper that should be cited for ginga?

There are two or three that can be cited. Let me dig up the references and I'll add them to this issue.

> And do you have manpages for the binaries? I can create them myself, but if there is already something, I would take it :-) (We need manpages for every program in Debian).

There are none currently.  Is there a facility for creating them from docutils markup?  If so, I can help with that.

**Comment by olebole** [comment]
I added these recommendations and suggestions. For the alternative backends: I marked them as alternatives, `python-pyqt5 | python-qt4 | python-gtk2` (for Python 3 without gtk2 because of the missing cairo lib). I would ignore tkinter for the moment (quite oldstyle), and would put the tornado backend into a "Suggests" -- it seems quite special. Kapteyn is not available in Debian yet.

For the ginga _program_, I will create a separate package, based on Python 3. This will _depend_ on `python3-pyqt5 | python3-qt4`, since it is not usable without a backend at all.

For the manpage, there is a `rst2man` in the `python3-docutils` package.

**Comment by ejeschke** [comment]
@olebole, what is your opinion on the prevalence on qt5 packages in debian?  Is qt4 considered more "stable" with python3?

**Comment by olebole** [comment]
No idea. If there are no drawbacks, I would always go with the most recent version. This helps to find and remove bugs there, and if it turns out to be really unstable, we can always go back. Since they are listed as alternatives, one can always go and install the other backend instead if one likes this more.

**Comment by olebole** [comment]
I just enabled the creation of some basic manpages from the `--help` output of the programs. This was mainly the last showstopper before creating the Debian package.
Do you have any more comments? Otherwise I would just go and upload the package.

**Comment by ejeschke** [comment]
Just one more, I think.  Does "python-pil" pull in the old PIL or the new "pillow"?  Do they coexist under Debian?  If so, how does one distinguish at the python import stage?

Thanks again for working on this.  I'm planning to add the paper citations as a bibtex file in the package.  I'll post an update here when I've done that.

**Comment by olebole** [comment]
python-pil is pillow.  The PIL code is not in Debian anymore.

**Comment by ejeschke** [comment]
Excellent.  Then I don't see any reason we can't release the package.

**Comment by olebole** [comment]
I uploaded the package; once it is accepted we can probably close this issue.

**Comment by ejeschke** [comment]
Let's leave it open until I get the references file added.  We maybe could do a better man page as well.

I'm wondering if the man page could be generated from the [quick reference](https://ginga.readthedocs.io/en/latest/quickref.html)

**Comment by olebole** [comment]
It can somehow; but tables don't look very nice in a manpage (and there seems to be a bug either in rst2man or in the manpage viewer that sometimes gets the line drawings wrong). If you could rewrite the page into a list, it would help much.
Also, that page is still not included in the source (pypi) distribution, right?

**Comment by ejeschke** [comment]
@olebole, I've added a file (`doc/ginga_papers.bib`) that contains a short bibliography of papers published about Ginga.

Regarding the man page, I find it a pain to maintain the table in the quickref anyway.  I'm thinking it might be better to do that as paragraphs with bulleted lists. Would that work better?

In any case, maybe we should check in the man page into the repo?  If we do something in `docutils` markup at least it would stand a good chance of being maintained.

**Comment by olebole** [comment]
Which if your papers would you consider as _the_ reference?
One [problem](https://bugs.debian.org/825196) was discovered with the current package: I installed the `grc` script to `/usr/bin/`; however this conflicts with the binary of the [grc](https://packages.debian.org/stretch/grc) package in Debian. Since `grc` is just an example script, I removed it from `/usr/bin/`. Would it make sense to include as example (so, under `/usr/share/doc/ginga/examples/`)?

**Comment by ejeschke** [comment]
Well, `grc` is not an example script, it is the remote control program for the reference viewer ("Ginga Remote Control"). I suppose it would be ok to change the name, but surely this problem happens with other packages in Debian. If two packages use the same name, how is that handled if there is a conflict?

**Comment by ejeschke** [comment]
I'll take a quick review of the papers to see which one should be the canonical reference.

**Comment by olebole** [comment]
For `grc`, you should then change the misleading introductory comment line in the script ;-)
```
# grc -- Ginga Remote Control example client
```
What would be a better name? Maybe `ginga-client`?

Generally, in Debian we have a "first comes" rule, however depending a bit on the importance of the package. If there is really no choice, one can mark two packages as "Conflicts" so that they can't be installed together. This would however also require to lower the priority of the package. Another possibility is to put the scripts in a "private" path, but this would need from the user to add this to his `$PATH`. So, if possible, the script should be renamed.

**Comment by ejeschke** [comment]
@olebole, what is the other package that contains a "grc" program?

**Comment by ejeschke** [comment]
If we rename the remote control client I'd like to give it a short name, if possible, because one might to type it from the command line over and over. @olebole do you have a suggestion for a short name that is not taken by the usual Debian packages?

**Comment by olebole** [comment]
The package is [grc -- generic colouriser for everything](https://packages.debian.org/jessie/grc). The problem with short names is that they are often taken, and there is no comprehensive list for them. I can, however, check individual proposals ([here](https://www.debian.org/distrib/packages#search_contents))

I would use "ginga-client". Although it is not short, it is descriptive, and with tab completition it also does not need more keystrokes.

**Comment by ejeschke** [comment]
How about "girc"? It looks like it might not be taken.

**Comment by ejeschke** [comment]
Or maybe "ggrc"?

**Comment by olebole** [comment]
As you like. We can take any name that is not already taken.

**Comment by ejeschke** [comment]
Ok, I've merged #350, which should rename `grc` to `ggrc`.  @olebole, does the debian package get created from the PyPI release?  If so, thinking I should bump the release number and make one.

**Comment by olebole** [comment]
Yes, I take PyPI as the download location.

**Comment by ejeschke** [comment]
I've pushed a new release up to PyPI, incorporating all recent fixes.

**Comment by ejeschke** [comment]
@olebole , if this fixes all remaining issues for creating the package, I think we can close this issue.

**Comment by olebole** [comment]
Since the new package version is now in Debian since a week without problems, I am going toclose the issue.

**Comment by ejeschke** [comment]
@olebole, I had some discussion with some other Ginga developers about how to institute a release cycle that makes it easier to tell when to make a debian release.  We found that since Ginga is using the `astropy_helpers` template it can auto-generate a version number based on the git hash if "dev" is the prefix in the release part of the "major.minor.release" version number (i.e. 2.5.dev will generate something like 2.5.devXXXX).

My idea is to use github releases to mark the major releases (which will not have the "dev" prefix in the third position.  After this, you would know to update the debian release whenever there is a non-"dev" release.   I'm thinking of using github release feature to tag the non-dev releases and there would be more extensive notes in the changelog of those about what has been fixed, enhanced, etc.  What do you think of this idea?

**Comment by olebole** [comment]
Sounds fine, except that I don't know exactly how the automated numbering by `astropy_helpers` is done. I can parse the github tags (or pypi, whatever you prefer here) by omitting the `dev` versions. However, the version number will be explicitely in the package, right?

**Comment by ejeschke** [comment]
Yes, just as it is now.  It's just that the "dev" versions will be a signal that there is no urgent need to update the debian package.

**Comment by olebole** [comment]
That is great.
BTW, if you have a feature that you need to be test built on Debian before the release, you can also create an "RC", which I would then package into our "experimental" tree.

**Comment by ejeschke** [comment]
Ok, great.  To kick this off, I'm going to make a release (2.6.0), and then immediately change the version to a (2.7.devXXXX).  I'll close this issue again when I've done that.

**Comment by ejeschke** [comment]
Ok, versioning changed and we are on the new system, which is PEP 440 compliant.

**Comment by olebole** [comment]
Hi Eric, thank you very much! I'll test and package this ASAP.
