### ISSUE TITLE
Registering custom plugins

### ISSUE THREAD

**Issue by pllim** [ejeschke/ginga#207]
"I like the idea of plugins registering themselves somehow on the install so that there is no need for autodiscovery." -- @ejeschke 

https://pythonhosted.org/setuptools/setuptools.html#dynamic-discovery-of-services-and-plugins -- @embray

Instead of shared namespace solution (as discussed in #92).

c/c: @eteq

**Comment by pllim** [comment]
OMG I just c/c-ed three Eric/Erik's

**Comment by embray** [comment]
I've mentioned before that this can be done with entry_points.  Here's a decent primer: http://pylons-webframework.readthedocs.org/en/latest/advanced_pylons/entry_points_and_plugins.html  (not specific to Pylons in any way).

**Comment by pllim** [comment]
> *"Now that the plugin is written we need to write the code in the CMS package to load it."*

Does this mean Ginga's setup needs to acknowledge the external plugins for this to work?

What if the external plugin comes with its own data files or utility functions?

**Comment by eteq** [comment]
@embray - I've always been afraid of these entry points on the theory that they are a setuptools thing that doesn't clearly have a future.  Do you know if the `distutils2` et al. discussions have said this will continue to work in the future?

@pllim - yes, ginga would have to support this in its plugin loading machinery, but I think it would be pretty straightforward to just iterate over the entry points and have them return plugin classes.

My main concern is that I'm not sure this is *desired*: that is, should ginga really automatically show *all* plugins that are installed without the user having to do anything?  It might be that, at least for the reference viewer, the answer is yes.  But it might be confusing for a lot of users when they start seeing a bunch of plugins and have no idea where they came from.

**Comment by pllim** [comment]
> ginga would have to support this in its plugin loading machinery

Not sure if I like this part. That means @ejeschke would have to review and sanction every single external plugin that people write. Maintainability can be a problem here.

**Comment by eteq** [comment]
@pllim - not quite manual - he'd just have to set up the *machinery* - that is, he just writes some code that says "if some package on the pythonpath registers into the ``ginga::local_plugin``, call the `load_plugin` method on it".  Then the plugin packages just say "I register with ``ginga::local_plugin``", and then every time ginga starts up it should load that plugin.  But there's no need for `ginga` to *explicitly* keep track of specific plugins.

**Comment by ejeschke** [comment]
@pllim, I certainly don't want to be in the business of doing that!

I'm wondering if we can do this in the form of a file that gets written when the plugin is registered.  Ideally the file is human-readable (json-maybe?) so the user could manually go in and comment out plugins, edit things, or even just delete or move the file elsewhere to startup ginga with a "clean slate". 

Another possibility would be to have each plugin represented by a file in a directory, that contains configuration information for the plugin.  Ginga then just has to scan the directory for files and load those plugins.  This would also allow you to install the plugins in different places, because the configuration could have information about modules, extra data files, etc.  When ginga is installed it would write the directory with the standard set of plugins, and the user would be free to remove any or all of them.

**Comment by pllim** [comment]
@eteq , but he still has to keep track of a list of external packages, no?

**Comment by eteq** [comment]
@pllim - no, that's the beauty and curse of entry points: the main package has no control of who registers into the entry point. So on one hand it means users can install any plugin and have it just work. On the other hand... The same thing: users can install a plugin that abuses or breaks ginga in a way the main project knows nothing about.

**Comment by pllim** [comment]
Personally, I am fine with just using one of the distribution options below that already work:

1. #169 (namespace package with no auto-discovery) and explicit plugin loading by the user. 
2. Using existing Ginga plugin machinery (without shared namespace) and more complicated loading codes (see https://github.com/spacetelescope/stginga/blob/master/stginga/plugin_info.py by @eteq).

And if a user has a random standalone plugin, the existing machinery is to store it in `~/.ginga/plugins` directory. Not very distributable but might just work for a regular astronomer who just want to publish a paper.

Let me c/c @stscieisenhamer, since he is also developing some plugins.

**Comment by eteq** [comment]
@ejeschke As I said above I'm pretty sure you don't *have* to manually accept specific packages, but it's not always desirable to do it automatically. But maybe the thing to do is have then auto-discover but not auto-run, and instead have a thing pop up that tells the user that a plugin is installed but they have to do something manually to get it to actually activate it?

**Comment by pllim** [comment]
>  a thing pop up that tells the user that a plugin is installed but they have to do something manually to get it to actually activate it?

@eteq , that sounds reasonable. But I think a command line argument or Python function would be better than a pop-up? Examples:

```
$ ginga --find-custom-plugins
12 custom plugins found
~/.ginga/plugins/myplugin1.py
/some/path/myplugin2.py
/some/other/path/myplugin3.py
...
```

```python
>>> import ginga
>>> ginga.find_custom_plugins()
12 custom plugins found
~/.ginga/plugins/myplugin1.py
/some/path/myplugin2.py
/some/other/path/myplugin3.py
...
```

**Comment by pllim** [comment]
Not sure if this is helpful, but I started and then abandoned something like that for shared namespace solution at https://github.com/pllim/ginga/tree/namespace-tools . FYI.

**Comment by ejeschke** [comment]
Just for the record, it is possible currently to edit `$HOME/.ginga/ginga_config.py` to manually register any plugins, or add catalogs, etc.  But I think there should be a simpler scheme for plugins along the lines of what we are discussing above.

**Comment by embray** [comment]
setuptools is going to be around for a very long time still.  Lots of projects use entry_points.

**Comment by embray** [comment]
> My main concern is that I'm not sure this is desired: that is, should ginga really automatically show all plugins that are installed without the user having to do anything? It might be that, at least for the reference viewer, the answer is yes. But it might be confusing for a lot of users when they start seeing a bunch of plugins and have no idea where they came from.

In Trac plugins are discovered automatically via entry_points, but still have to be activated manually by updating the config file.

**Comment by eteq** [comment]
@pllim -  I think your 2 is just fine - it has been fine for `stginga`, now that we know how to do it (and that may well serve as sort of implicit documentation for other packages to follow).  But I'm generally against namespace packages because I think it makes it a lot more confusing how things fit together either for users who need to report bugs or novice devs (e.g. users who want to just write a plugin).  Either way, though, I think auto-discovery along the lines of this discussion is sort of a "bonus": it makes things a bit easier, but is not really critical.

If it does make sense to go forward with autodiscovery, I was thinking the main purpose is to try to make it as trivial as possible on the user (without going all the way to "everything is automatically loaded no matter what").  As @pllim says, it's already possible to do it if you're moderately comfortable working with config files, so autodiscovery doesn't seem that valuable unless it's easy for novices.  So I guess what's in my head is that an auto-discovered/`entry_points` plugin would lead to some sort of in-gui either dialog or panel that could be used to opt-in to plugins.  The natural way would be to keep the "opted-in" list in ``ginga_config.py``, so the power-user can just do it directly in the config file that way if they want, a la what @embray mentioned re: Trac.

**Comment by ejeschke** [comment]
I've floated a trial balloon in PR #230.

**Comment by ejeschke** [comment]
Superseded by #426
