### ISSUE TITLE
Include ginga glue plugin in ginga, not glue

### ISSUE THREAD

**Issue by astrofrog** [ejeschke/ginga#231]
I noticed today that the ginga plugin to glue is broken again due to changes in the API in ginga. We now have a mechanism in place for allowing external packages to register plugins with glue, so I was thinking that it might make more sense to include the ginga plugin for glue in ginga, otherwise we'd have to have some complicated logic in glue to behave differently depending on the version of ginga.

@ejeschke - would you be happy for the plugin to live at `ginga.glue`? If so, I can open a pull request adding the plugin here and setting up a Travis build configuration to run the tests with the latest stable version of glue. Would that work for you?

cc @ChrisBeaumont @jegpeek

**Comment by ejeschke** [comment]
@astrofrog, I'm fine to change how the plugin is distributed.  Let me think a little bit about where that should live.

**Comment by ejeschke** [comment]
@astrofrog, how are you handling distributing 3rd party plugins for glue?  I think this should be treated the same way.  For example, if there is a way to make a `setup.py` script that registers and installs this as a glue plugin.  Because it is a glue plugin I don't think it makes sense to bundle it with ginga--ginga is just a requirement for this plugin like any other module might be for a 3rd party glue plugin.

I'd be happy to host it, and even help author the setup script if I can get your glue expertise.

**Comment by ChrisBeaumont** [comment]
@ejeschke @astrofrog I'm not sure where I stand on this issue. On the one hand glue-ginga integration seems to break fairly often because the ginga api changes more frequently than other glue dependencies, and it's not feasible for Glue to test against every ginga api change in it's continuous integration setup. Ginga, on the other hand, could choose to include glue-integration tests, to guarantee that any given version of ginga is compatible with Glue (whose on API evolves more slowly). 

However that's asking a lot of Ginga. So the feasible options are:
* The glue plugin is provided and tested by Ginga, but a glue dev "owns" the maintenance of that in the ginga repo.
* Glue continues to host the plugin, but is more strict with the user to ensure that they are using a "verified" version of Ginga

**Comment by ejeschke** [comment]
It's a bit of a chicken and egg thing, isn't it?  If we do consider it from the perspective of a third-party glue plugin developer, then I suppose the onus is on me (and others interested in the functionality) to keep the plugin up to date with glue.  If the glue API isn't changing so frequently then that shouldn't be too hard.

I think it makes sense to keep it glue only if the glue maintainers consider it a useful enough addition to want it to be built in.  That's not the message I'm sensing from @astrofrog, so I'm comfortable packaging it as an add-on and hosting it at my github page right beside ginga.  We'd just need to set up a minimal package with an installation script that knows how to install it or some instructions if it is a manual process.

**Comment by astrofrog** [comment]
Just as a quick note, there has been another API change that affects glue: https://github.com/glue-viz/glue/pull/815

**Comment by ejeschke** [comment]
If I look at the current ginga code for wcs handling, I have handing for 0.2, 0.3, 0.4-0.9, and 1.0-> versions of astropy where the API changed or some aspect coordinate handling changed.  I have also had to work around changes in API for Qt, numpy and other 3rd party packages.  So I don't think it is just ginga that changes API occasionally--this is a fact of life of using active packages that evolve.

ginga has a versioning scheme that follows the convention of monotonically increasing values. So it would be possible to fix the release if you want to do that.  I'm also fine to break out the plugin and handle it as a 3rd party plugin.  Just let me know how you would like to proceed, @astrofrog.

**Comment by ejeschke** [comment]
This has been taken out of glue and put [here](https://github.com/ejeschke/glue-ginga), as discussed above.
