### ISSUE TITLE
Plugin auto redo when remove-image callback is issued?

### ISSUE THREAD

**Issue by pllim** [ejeschke/ginga#264]
I notice that local plugins do not update when I remove an image. So, I have to add this in my plugins:
```python
fv.add_callback('remove-image', lambda *args: self.redo())
```

I wonder if this is something that should be done automatically in `ginga/Control.py` instead. What do you think, @ejeschke ?

**Comment by ejeschke** [comment]
If the image removed is the "current" image, and it causes a change to a new image, `redo()` should indeed be called.  However, I think right now deleting an image from a channel does not cause it to be removed from the channel viewer.  That might be a reasonable behavior.  So also it might be to switch to another image in the channel (e.g. the "next" image). 

Do you think it should switch to a new image, @pllim?

**Comment by pllim** [comment]
Hmm... Good point.

Right now, my `redo()` methods check to see if an image is being displayed and does nothing is image is `None`, which effectively clears the values my plugin GUI. I have not considered the situation where the plugin does not have this check in its `redo()`.

Whether changing to next image or not does not address the issue above, because what if there is no more image to switch to?

I am not sure what is the best way to address such a situation in Ginga itself. Feel free to close this if you do not think this is applicable to `Control.py`. I can just keep that `add_callback(...)` line in my own plugins.

**Comment by ejeschke** [comment]
I think `redo()` should only be called if the channel viewer image changes.

Whether the viewer image should change if it is removed from a channel is another question.  I don't have a strong opinion on the matter, since we almost never use the `remove` feature.  It seems to me that both of the above behaviors might be considered appropriate.  At least in the current case, it means that the choice of the next image viewed is up to the user, at which point `redo()` will be called...

**Comment by pllim** [comment]
Okay, sounds reasonable. Let's just close this.
