### ISSUE TITLE
Ginga silently suppresses some exceptions 

### ISSUE THREAD

**Issue by pllim** [ejeschke/ginga#290]
I am not sure when this started happening but I noticed that with the latest dev, Ginga does not report some exceptions, which complicates some debugging process.

For example, I have a plugin that calls:

```python
dat = mobj.get_image().get_data()  # This returns data array from RGBImage
obj = self.dc.Image(0, 0, masktorgb(dat, color='white', alpha=1.0))
```

It is supposed to raise `ValueError` (see `masktorgb()` function in `ginga/util/dp.py`). But Ginga does not report this at all. So I was left wondering why nothing happens. To debug, I had to explicitly catch and report the exception myself, as follows:

```python
try:
    obj = self.dc.Image(0, 0, masktorgb(dat, color='white', alpha=1.0))
except Exception as e:
    print(e.__class__.__name__, str(e))
```

Is this intentional?

**Comment by ejeschke** [comment]
@pllim, I'm not aware of any recent changes that should have changed exception handling. But I believe that if the exception happens in a callback it may not be reported unless the `make_callback` is inside a try/except handling block.

There is a useful function called `error_wrap()` in `Control.py`.  You can use this to make a function call that will log any error (along with a traceback) and pop up the error in the `Errors` plugin.

**Comment by pllim** [comment]
For this particular case, that code was in a method that is connected to the `'selected'` signal in a `TreeView`. Does that count as a callback? The signature of the method is as follows:

```python
def hl_table2canvas(self, w, res_dict):
    # blah blah
```

**Comment by ejeschke** [comment]
Yes, it does.  In particular, callbacks from UI events often are not called from within a try/except block, while callbacks from "deeper" in the code generally are.  If you are calling something significant from a UI event it's generally a good idea to use the `error_wrap` method if you just want to be made aware of any error, and your own try/except clause if it's critical to handle the error in a certain way.

For UI event-driven programming most events kind of originate within the bowels of the windowing system and then through the python UI toolkit--so they are "top level" wrt the user's program. Ginga does intercept most of these calls using the widget wrapping machinery, but I think there would be trade-offs to redirecting all of them through some kind of general try/except.  The problem is, if a user want's to catch the error with try/except and handle it, you don't necessarily want to intercept it and log it as an error without understanding the context.

**Comment by pllim** [comment]
Okay. Thanks for the clarifications!
