### ISSUE TITLE
Operations menu to handle a lot of local plugins

### ISSUE THREAD

**Issue by pllim** [ejeschke/ginga#310]
The number of plugins are getting to the point that current `Operations` dialog is not going to be sufficient. Some ideas below:
- Some kind of scrolling mechanism
- Separating them into categories -- But what if a plugin can fall into multiple ones? How do users instinctively know which category to look for a certain plugin?
- Multi-column menu
- Anything else?

**Comment by ejeschke** [comment]
@pllim this issue is partially addressed in commit 3364b3206dc8f64a945b3567d8062ce3d39fe0dd.

We can now specify categories for plugins and it will make nested menus under those categories.  I'm not suggesting that as a full solution to the issue, but it's a capability we could use.  See [main](https://github.com/ejeschke/ginga/blob/master/ginga/rv/main.py) spec entries for plugins for examples of how the categories are set.  If no category is specified for a local plugin it gets put in at top-level; if none is specified for a global it goes in under "Global".

If you put a "." in the category, it creates a sub-category.  When you get a chance, play with it a bit and see if that seems like something we could use to wrangle some order into the increasingly large list of plugins.
