### ISSUE TITLE
ginga seg fault under conda and qt5

### ISSUE THREAD

**Issue by Cadair** [ejeschke/ginga#415]
I built a conda env that looked like this:

```
name: ginga-dev
channels: !!python/tuple
- defaults
- conda-forge
- astropy
dependencies:
- astropy=1.2.1=np111py35_0
- astropy::ginga=2.6.0=py35_0
- dbus=1.10.10=0
- expat=2.1.0=0
- fontconfig=2.11.1=6
- freetype=2.5.5=1
- glib=2.43.0=1
- gst-plugins-base=1.8.0=0
- gstreamer=1.8.0=0
- icu=54.1=0
- jbig=2.1=0
- jpeg=8d=2
- libffi=3.2.1=0
- libgcc=5.2.0=0
- libiconv=1.14=0
- libpng=1.6.22=0
- libtiff=4.0.6=2
- libxcb=1.12=1
- libxml2=2.9.4=0
- mkl=11.3.3=0
- numpy=1.11.2=py35_0
- openssl=1.0.2j=0
- pillow=3.4.2=py35_0
- pip=9.0.1=py35_1
- pyqt=5.6.0=py35_0
- python=3.5.2=0
- qt=5.6.0=1
- readline=6.2=2
- setuptools=27.2.0=py35_0
- sip=4.18=py35_0
- sqlite=3.13.0=0
- tk=8.5.18=0
- wheel=0.29.0=py35_0
- xz=5.2.2=0
- zlib=1.2.8=3
```
under arch linux and when I run ginga, it starts ok until I mouse over the menu bar then it crashes with the following error:

```
libgcc_s.so.1 must be installed for pthread_cancel to work

Aborted (core dumped)
```

**Comment by Cadair** [comment]
I tested this with pyqt4 and it does not exhibit the error

**Comment by ejeschke** [comment]
@Cadair, I am also seeing some stability issues with python 3 + qt5 on Linux, but it doesn't happen just mousing over a menu (I have to push it a bit).  Could you set logging to debug with "--loglevel=10 --log=ginga.log" and capture whatever you can before the crash?

In my testing on Ubuntu 16.04, I got the following results:
- python2 + qt4: fine
- python2 + qt5: fine
- python3 + qt4: fine
- python3 + qt5: some issues

Also, I cannot reproduce any of the issues with python3 + qt5 on the mac.

**Comment by pllim** [comment]
What's your GCC version?

**Comment by Cadair** [comment]
```
 ❯ gcc --version
gcc (GCC) 6.2.1 20160830
```

**Comment by Cadair** [comment]
that's system gcc fwiw

**Comment by pllim** [comment]
Mine is still `gcc (GCC) 4.4.7 20120313 (Red Hat 4.4.7-17)` :sweat_smile:   I switched to Qt4 a few weeks ago but haven't seen any segfault. But then again, I am not mousing over menus that fast. Thanks for reporting this, I'll keep an eye out.

**Comment by ejeschke** [comment]
```bash
$ gcc --version
gcc (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609
```

But I'm not positive this exact version was used to compile Qt5 on this system.  I'd say it is likely.

**Comment by ejeschke** [comment]
On Mac OS X it seems to be:
```bash
(py3k) MacBook-Pro-2:Ginga eric$ gcc --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include/c++/4.2.1
Apple LLVM version 8.0.0 (clang-800.0.42.1)
Target: x86_64-apple-darwin15.6.0
Thread model: posix
```

**Comment by pllim** [comment]
What do you see when you do `gcc -print-file-name=libgcc_s.so.1`? Mine is `/lib/../lib64/libgcc_s.so.1`. But at the same time, I also have `libgcc 5.2.0` via Anaconda. I wonder if yours are somehow incompatible with each other.

From a quick Google search, I found https://www.gnu.org/software/gcc/gcc-3.0/libgcc.html that says, "If two shared objects (or one shared object and a main program) are linked against different versions of libgcc havoc may ensue."

Not sure what the proper solution would be in this case...

**Comment by pllim** [comment]
Just to note here for the record: I tested latest dev Ginga with Qt5 on RHEL6 64-bit under both Python 2.7 and 3.5. I could not reproduce segfault when mousing over menu. However, when I mouse over image while adjusting contrast really really fast (much faster than someone would use Ginga for in real life) for several seconds straight, I did get segfault in *both* Python 2 and 3. @ejeschke thinks it is due to stack overflow of mouse events. On Python 3, I reproduced it and captured the traceback using `gdb`, which resulted in over 15k levels of traceback, which is not very useful in debugging but further supports Eric's theory.

**Comment by Cadair** [comment]
To clarify on the "menu" thing, I moved my mouse at normal speed from roughly the centre of the window (over the image) to the file menu in the top left. I did this twice and it seemed to crash when my mouse entered the menu bar both times.

**Comment by pllim** [comment]
Re: menu thing. Still can't reproduce it. How many images did you have open? Does it still crash when you have no image loaded at all? Could it be that your installation (gcc, ginga, or whatever) is somehow corrupted?

**Comment by ejeschke** [comment]
@Cadair, can you try to upgrade Qt to 5.6.2 in your conda, and report back the result?  I'm not sure it is related to this issue, but see my next message below.  Also, that is the version I am running on Mac OS X without any crash problems.

**Comment by ejeschke** [comment]
So I took a good long look at this yesterday.  The good news is that the problem @pllim and I can force to happen on Linux appears to be a Qt 5 issue that is probably fixed in Qt 5.6 (or some patch level above that).  Apparently on early versions of Qt 5 the normal mouse motion compression that is done has a bug so that many, many more mouse events get propagated through to the application than is the case under Qt 4.  There are a number of links to examples of things that match how we can make it crash by extremely rapid and lengthy mouse movement. A sample: [1](http://lists.qt-project.org/pipermail/development/2014-December/019401.html), [2](https://codereview.qt-project.org/#/c/108275/), [3](https://bugreports.qt.io/browse/QTBUG-40889) , [4](http://vtk.1045678.n5.nabble.com/Delayed-mouse-interaction-due-to-event-loop-bug-in-Qt5-td5730474.html) and [5 arch linux example](https://bugs.archlinux.org/task/47650).

I am going to briefly look at a workaround, but depending on the complexity it may not be worth it considering that under normal use this is not likely to occur.

I think this is a separate issue from just having the app crash from mousing over the menu, which sounds very much like a Qt 5 bug under that particular configuration that @Cadair reported.

**Comment by ejeschke** [comment]
@pllim, could you try commit e822c2018dda86aeec85bb0d68bd511567af221a or later?  I believe this works around the known issue with rapid mouse movement.  I'd like to know whether it solves the issue @Cadair was having as well.

**Comment by pllim** [comment]
@ejeschke , sorry for the wait. I finally have a chance to test this -- Moving the mouse around really fast while adjusting contrast does not crash anymore. Thank you!

**Comment by ejeschke** [comment]
Excellent.  I think we just need to hear from @Cadair before we close this issue.

**Comment by ejeschke** [comment]
Closing this issue.  We can reopen if someone reports a crash with Qt 5 again under similar circumstances.
