### ISSUE TITLE
PixTable listing reverses displayed columns

### ISSUE THREAD

**Issue by pllim** [ejeschke/ginga#436]
![screenshot](https://cloud.githubusercontent.com/assets/2090236/23269615/2e048c36-f9bf-11e6-92c0-4108b9d66bf9.png)

What I expect to see:
```
0       0        0        0
0       0       -1        0
0       0      -13.5      0
0       0        999      0
0    -19.17    -25.5      0
```

**Comment by ejeschke** [comment]
Good catch, @pllim!  I expect that is because of the inverted nature of the Y axis of FITS data compared to "regular" computer graphics.  Should be easily fixable by flipping the cutout in Y direction before proceeding.

But this leads me to wonder whether we need to match the users transformations.  Suppose the user had inverted X and Y axes, or rotated the image 180 deg.  Does the printout always have to follow this?  It may be difficult.

**Comment by pllim** [comment]
> But this leads me to wonder whether we need to match the users transformations.

I almost never rotate/reverse the image, so this is not important to me. Perhaps for now, just mention in the instructions that this plugin does not support such transformations?

**Comment by ejeschke** [comment]
@pllim, could you try commit 377791751a96947b75c8f7cbabfd110199ecf4ff?

I also improved the pixtable documentation.

**Comment by pllim** [comment]
Thanks, seems to work fine now!
