### ISSUE TITLE
Feature Request: Add option to pop out Help text into a separate window

### ISSUE THREAD

**Issue by pllim** [ejeschke/ginga#438]
This is how Help currently displays for me, which requires me to either scroll back-and-forth non-stop or adjust the right panel (making image display area smaller), none of which is ideal for me.

![screenshot](https://cloud.githubusercontent.com/assets/2090236/23760801/c695bcea-04be-11e7-94cd-162c18b5df23.png)

While I understand that you prefer not to have too many windows open, I also would still like an option for separate window for Help text. However, as a compromise, we can have this feature purely optional via user clicking a button that clearly states the Help text would create a new window. What do you think?

**Comment by ejeschke** [comment]
Hi @pllim,
I don't have any real problem with a pop out.  Ideally that could be a preference that you set in `general.cfg`.

I think the real issue though is that the text does not wrap nicely.  I played around a little bit with the docutils functions for generating HTML.  I'm wondering whether could have a solution that checked whether the webkit widget was installed (used by `WBrowser` plugin, currently) and also `docutils`, and if they are present it would render the class docstring as a web page in the plugin.  This would make the text flow smoothly and you'd only have to scroll vertically.  What do you think?

**Comment by pllim** [comment]
@ejeschke , as long as I don't have to scroll left-right continuously, I am open to the ideal of HTML rendering.

**Comment by ejeschke** [comment]
@pllim, I've updated the `TVMark`, `TVMask`, `ChangeHistory` and `SaveImage` to use the new help mechanism.  I've pretty much just inserted the ReST markup from the manual pages, and tweaked it a bit so that it renders without references to the rest of the manual (which give a nasty error message, since they are not available--things like cross-references, etc.).

**Comment by ejeschke** [comment]
We might want to add `docutils` as a recommended package to install (or maybe even required?).

Also think about making it so that the images can be rendered into the help.  As we discussed offline, this might entail moving the documentation so that it installs with the package.  But I'm not sure that is the best way to proceed.

**Comment by pllim** [comment]
Re: docutils

Technically, Ginga can still function without docutils. So, you can certainly list it as optional dependency. I see that you already have `have_docutils` in `Control.py`, so all you need to do is add a logic to handle `have_docutils = False` and display some generic error message when `Help` is pressed.

Re: package data

When the full rendered doc is somehow available as package data, can `Help` then just re-direct to `WBrowser`?

**Comment by ejeschke** [comment]
> so all you need to do is add a logic to handle have_docutils = False and display some generic error message when Help is pressed.

Currently it just creates a text widget as before and displays the full ReST text in the docstring.  I think this is not a bad fallback.

> When the full rendered doc is somehow available as package data, can Help then just re-direct to WBrowser?

That's the idea. 

`WBrowser` used to just link to the manual.  If there was a local copy of the HTML it would use that, otherwise it would try to go to the internet.  Maybe just having the Help functions try to access the manual pages online first, and then fall back to rendering just the class docstring if that fails?

The issues as I see it are:
1) maintaining two sets of documentation is not a good idea
2) the user may not have the webkit browser installed
3) the user may not have docutils installed
4) the user may not be connected to the internet

**Comment by pllim** [comment]
*Theoretically*, one of these might be possible...

* Have `setup.py` attempt a Sphinx build and store rendered HTML as package data for distribution/installation. This might be overly complicated and easily breakable.
* Manually generate HTML doc with Sphinx and add them as package data. This can easily get out-of-sync with RTD if developer is not diligent in manual doc generation when code changes.

**Comment by pllim** [comment]
> maintaining two sets of documentation is not a good idea

I totally agree, @ejeschke !

**Comment by pllim** [comment]
I think this issue is solved.
