### ISSUE TITLE
Cannot switch image via Thumbs when MultiDim is active

### ISSUE THREAD

**Issue by pllim** [ejeschke/ginga#459]
You can reproduce with the following steps:

1. Open an image with multiple extensions. In my case, image display chooses Extension 1 (as EXT 0 is just a header).
2. Open `MultiDim`. For whatever reason, it automatically jumps to EXT 0, which is the primary header.
3. Now I click on EXT1 thumbnail on `Thumbs` but it will not switch image display to EXT1. Instead the highlighting jumps back to EXT0 thumbnail.
4. Only when I change the extension via `MultiDim`, I can actually switch the displayed image.

**Comment by ejeschke** [comment]
I think this may be a limitation of the way that plugins do not know so much about each other.  The problem is that when you click a thumbnail for a new image it will cause the `redo()` function in `MultiDim` to fire, and it will *reopen* the file and use it's logic to find the first available HDU to display.

To change this behavior, `MultiDim` needs to become a little more sophisticated.  One option that wouldn't cause too much trouble would be to simply have `MultiDim` reopen the image but *not to display anything*, but to identify the HDU that is being displayed and simply set the controls to match it.

**Comment by ejeschke** [comment]
Try commenting out the `set_hdu()` call on line 577 in `MultiDim`.  Does this work?

**Comment by ejeschke** [comment]
> Try commenting out the set_hdu() call on line 577 in MultiDim.

For me this keeps `MultiDim` from overriding the image.  But the `idx` metadata item seems not to be set correctly in the images, so that the correct HDU is not shown in the HDU selection control.

**Comment by ejeschke** [comment]
@pllim, commit a9943ebfb868e53bdb5d897db05617b06de282ba should partially fix this issue.

I believe that in some cases still, the correct entry in the `MultiDim` HDU selection control may not be shown when selecting images externally (e.g. via `Thumbs`).  But `MultiDim` should at least not override your selection of image anymore.

**Comment by pllim** [comment]
@ejeschke , thanks! Yes, I can switch image via Thumbs now. But clicking on a new image on Thumbs does not update the listing in MultiDim, as you mentioned.
