### ISSUE TITLE
Feature Request: Allow Pick to save out as ASCII table

### ISSUE THREAD

**Issue by pllim** [ejeschke/ginga#479]
Someone asked me why `Pick` only allows saving out to FITS table, not ASCII. The use case is that user wants to use the output with `tweakreg` (part of [DrizzlePac](http://drizzlepac.stsci.edu/)), which only accepts ASCII table.

**Comment by ejeschke** [comment]
Well, before I was using an ASCII table with comma delimited parameters.  I think the FITS table allows a little more flexibility in changing the columns and preserving all the precision of floats, etc.

Perhaps rather than supporting two formats we could make an easy converter that pulled the correct values out of the FITS table and wrote a CSV file in the exact format that `DrizzlePac` expects?

**Comment by pllim** [comment]
So, it could save to ASCII before! I am glad I was not going crazy.

It looks like the underlying machinery simply uses `astropy.table.Table.write()`, so why not just let Astropy table automatically handle the output format based on given extension?

**Comment by ejeschke** [comment]
> why not just let Astropy table automatically handle the output format based on given extension?

Perfect!
