### ISSUE TITLE
WCS conversion does not support multiple pixels at once (except for AstropyWCS)

### ISSUE THREAD

**Issue by pllim** [ejeschke/ginga#494]
In `wcsmod.py`, I found out that `pixtoradec()` method (at least for `astropy.wcs`) only works when single pixel `[X, Y]` coordinate is given. When I give `[[X1, Y1], [X2, Y2], ...]`, it breaks even though `astropy.wcs.WCS.all_pix2world()` can calculate for multiple pixels at the same time.

Is this a feature or a bug?

In an attempt to address #391 , the ability to calculate multiple locations at once is very desirable. To work around this, I need to directly access `all_pix2world()`, which limits the code to `astropy.wcs`, not any WCS package that user chooses to use.

**Comment by ejeschke** [comment]
> Is this a feature or a bug?

Neither, but just an omission in the initial design.  It would not be hard to support for all WCSes, since we could just do a cython iteration or some such for wcs packages that don't support array operations.  But I think that `kapteyn` does also support array operations, and maybe also `starlink-ast`.

It's been on my TODO list for a while, because it would also be very nice for the canvas graphics that use WCS coordinates to plot--because it could translate all the points at once.

If we do a PR like this we should also change the API so that the coordinates are passed in such that multi-dimensional points are supported; i.e. it is not `(x, y)`, but `(points)`.

**Comment by ejeschke** [comment]
I would suggest that if we undertake this PR, that we introduce a new call in the API for the `pixtoradec` replacement (also because you are not always converting to RA/DEC!)--this will minimize breakage of many things that rely on the current API.

**Comment by pllim** [comment]
The best I can do is implement that API for AstropyWCS and make the rest raise NotImplementedError, as I have never used those.

**Comment by ejeschke** [comment]
I'll help with the other ones.

**Comment by ejeschke** [comment]
I think we can close this, right @pllim?  API has been implemented for all wrappers, and 3 of them are truly vectorized (in the `numpy` sense).

**Comment by pllim** [comment]
Yes, thanks!
