### ISSUE TITLE
Why both LICENSE.txt and LICENSE.rst?

### ISSUE THREAD

**Issue by pllim** [ejeschke/ginga#503]
Seems redundant to have two copies of the same license.

**Comment by ejeschke** [comment]
LICENSE.rst is consistent with the rest of the restructured text documentation. Possibly it should exist inside the "doc" directory so that it can be linked to from the documentation.

However, "LICENSE.txt" appears at the top of nearly every code file in the project. And I think you need a file at the top level of the project for github to pick it up and display the license type icon properly.

**Comment by ejeschke** [comment]
I don't think it is too terrible to have two files with the same license in it.

**Comment by pllim** [comment]
Okay, just wondering. Thanks for the clarifications!
