### ISSUE TITLE
Add "save_layout" option to Customizing Ginga doc

### ISSUE THREAD

**Issue by pllim** [ejeschke/ginga#595]
As reported by @nluetzge , https://ginga.readthedocs.io/en/latest/manual/customizing.html#ch-customization does not document an easier way to customize Ginga window size and position using `save_layout` option in `~/.ginga/general.cfg`. As a result, user would attempt to use a more complicated way, which might not be necessary.

The `save_layout` option was added in 2d1085dc7b2b17f4

**Comment by ejeschke** [comment]
This issue is addressed in commit 490f3c5a265b7ae9ee75d8afd539603793b48789.

The default behavior of the reference viewer is now to save the window layout.  The viewer can be started with `--norestore` to prevent the restoration of the layout, or alternatively, `save_layout` can be set to `False` in `general.cfg`.

**Comment by pllim** [comment]
Thank you! It looks good.
