### ISSUE TITLE
MultiDim unexpectedly inserts entries into ChangeHistory

### ISSUE THREAD

**Issue by pllim** [ejeschke/ginga#602]
Workflow to reproduce the problem:

1. Start `MultiDim` local plugin.
2. Start `ChangeHistory` global plugin.
3. Load a data cube.
4. With `ChangeHistory` ("History" tab) in view, click on "next slice" (double-arrow) button on `MultiDim` and watch a new entry magically appears on `ChangeHistory` for that image.
5. Click on "next slice" again or "prev slice" to see another such entry.

Example screenshot:
![screenshot from 2017-10-24 14-22-46](https://user-images.githubusercontent.com/2090236/31960984-7198d9ee-b8c7-11e7-83d2-2da513ca5c79.png)

I suspect this is caused by either `block_callback('modified')` or `unblock_callback('modified')` in `MultiDim.py`. I just never caught this before until now because I rarely start up `ChangeHistory` with data cubes, but I think this has been happening for a while.

This bug is harmless but confusing, in the sense that it does not actually change the input data cube, but merely reported that it has done so.

**Comment by pllim** [comment]
> I suspect this is caused by either `block_callback('modified')` or `unblock_callback('modified')`

I commented those out and the bug is still there, so not them. Will continue to investigate...

**Comment by pllim** [comment]
Update: I tracked this to `image.set_naxispath(self.naxispath)` in `set_naxis()`, which in turn calls `image.set_data()`, which issues the `'modified'` callback that triggers `ChangeHistory`.

**Idea 1**

Modify `BaseImage.set_data()` to take one extra keyword that suppresses `self.make_callback('modified')` and have `set_data()` within `AstroImage.set_naxispath()` use this keyword.

Pro: Easy to implement.
Con: Might have unintended consequences.

**Idea 2**

After `image.set_naxispath(self.naxispath)` is called, use magical incantations given in `ChangeHistory` docstring to set `iminfo.reason_modified` to a special message. When `ChangeHistory` detects this special message, it will *not* add an entry.

Pro: Safer option.
Con: Is other plugins issue this special message without knowing what it does, they won't see entries in `ChangeHistory`.

**Comment by ejeschke** [comment]
The problem with Idea 1 is that a lot of different areas of code and/or plugins respond to the image modified callback in order to update their display or widgets (which they need to do, because the 2D image has changed!).  By shutting off that callback, it will be the case that some things won't update that should.

It seems to me that probably we want to have a higher level interface for modifications.  Perhaps a separate higher level API call in the ginga shell that says "this image has been modified with the following noted change" and then that triggers a separate callback that `ChangeHistory` would subscribe to.  And this would be associated with the ginga shell ("fv" thing) rather than the image itself.

**Comment by pllim** [comment]
@ejeschke , I agree that Idea 1 is not ideal. What do you think about my attempt at Idea 2 at #620? I still need to test if it really works.

**Comment by ejeschke** [comment]
Here is something like what I have in mind.  Currently, the `Mosaic` plugin does this:
```python
        # Add description for ChangeHistory
        try:
            iminfo = self.channel.get_image_info(self.img_mosaic.get('name'))
            iminfo.reason_modified = 'Added {0}'.format(
                ','.join([im.get('name') for im in images]))
        except KeyError:
            # mosaic image may have been deleted from channel
            pass

        loc = self.img_mosaic.mosaic_inline(images,
                                            bg_ref=bg_ref,
                                            trim_px=trim_px,
                                            merge=merge,
                                            allow_expand=allow_expand,
                                            expand_pad_deg=expand_pad_deg,
                                            suppress_callback=True)
```

Instead, it should do something like this:
```python
        loc = self.img_mosaic.mosaic_inline(images,
                                            bg_ref=bg_ref,
                                            trim_px=trim_px,
                                            merge=merge,
                                            allow_expand=allow_expand,
                                            expand_pad_deg=expand_pad_deg,
                                            suppress_callback=True)

        # Add description for ChangeHistory
        info = dict(time_modified=datetime.utcnow(),
                    reason_modified = 'Added {0}'.format(
                        ','.join([im.get('name') for im in images])))
        self.fv.update_image_info(self.img_mosaic, info)
```
i.e. make the change first, then call a high-level call to update the info.  As long as `ChangeHistory` has registered for the `add-image-info` callback, it will get the updated information.

This approach requires a small change in `ginga.rv.Channel` to remove the subscription and processing of the normal image `modiifed` callback, and the addition of an `update_image_info()` call in the `ginga.rv.Control` module (it should be there instead of in the channel class because an image can be loaded into multiple channels).  It also requires other plugins that are currently setting modification history with this older method to update to using the new API.

**Comment by ejeschke** [comment]
@pllim, I'll make a trial branch and update this issue with the link so you can try it out.

**Comment by ejeschke** [comment]
@pllim, please try [this branch](https://github.com/naojsoft/ginga/tree/new-change-notification).  You will need to update any plugins that make modification notices to follow the example in `Mosaic`.

If this works for you I will submit it as a PR.  I think it is cleaner than trying to guess which invocations of the 'modified' callback are significant.

**Comment by pllim** [comment]
@ejeschke , I agree that your solution is the right way to go (and it works with `Mosaic`). However, I am worried about backward compatibility. If I don't update the `stginga` plugins, the changes won't show up in the `ChangeHistory` anymore but there is no error message. Is it possible to issue an error when a plugin still uses the old `'modified'` callback?

**Comment by ejeschke** [comment]
> Is it possible to issue an error when a plugin still uses the old 'modified' callback?

Hmmm, I'm not suggesting to remove the 'modified' callback.  

Can you explain what kind of an error message you are thinking of (e.g. what would it say) and when one would see it?

**Comment by pllim** [comment]
Whilst the 'modified' callback is still there, it no longer has effect on `ChangeHistory`, thus breaking backward-compatibility.

> what kind of an error message you are thinking of

A message from `ChangeHistory` like, "An attempt was made to insert change history using the 'modified' callback, which is no longer supported. Please contact plugin developer to use <insert alternative> instead." What do you think?

**Comment by ejeschke** [comment]
I think it may be slightly difficult, due to the fact that the `modified` callback is in only *some* cases tied to changes that should be recorded in `ChangeHistory` and then only because the user set some particular metadata in the channel `info` for an image, prior to the change.  

One thing we might do is to detect that the plugin is trying to set the `reason_modified` attribute in the channel `info` for an image, and throw up an error message then.  We'd probably want to check very specifically for this attribute name, since there should be no real reason to disallow the plugin from otherwise adding arbitrary data to the info, as other plugins (e.g. `Thumbs`, etc) already do.

**Comment by pllim** [comment]
Looking at `ChangeHistory.redo()`, `reason_modified` is actually optional and defaults to "Not given" if not given. However, it will not insert an entry if `iminfo.time_modified is None`.

So, theoretically, `ChangeHistory` could catch any "modified" callback without "time_modified" and then emit the warning? Does that make sense?

**Comment by pllim** [comment]
@ejeschke , I'll run with my idea above and if it works, I'll submit a PR to your branch.

**Comment by ejeschke** [comment]
> So, theoretically, ChangeHistory could catch any "modified" callback without "time_modified" and then emit the warning? Does that make sense?

But then won't it catch many of the uses of `modified` that aren't meant for `ChangeHistory`?  In any case, feel free to try out your idea.

**Comment by ejeschke** [comment]
Ok, after looking at the particular combination of tests, I think your modification will work.  I'll merge it and submit as a PR.
