### ISSUE TITLE
[2.6.6] ginga_test_suite gone?

### ISSUE THREAD

**Issue by olebole** [ejeschke/ginga#614]
Hi Eric,

it was nice to see you at ADASS again :-) !

For Debian unit tests, I do a `python3 -m unittest "ginga.tests.ginga_test_suite"`, which [worked fine](https://ci.debian.net/data/autopkgtest/unstable/amd64/g/ginga/20171107_132933/log.gz) for previous versions. With 2.6.6, this is however gone (although still [mentioned](https://github.com/ejeschke/ginga/blob/241be7520f0c0168ed4a2018f7e18eaf1ec86d1f/setup.cfg#L31) in `setup.cfg`).

What is the best way now to run the (non-interactive) unit test on the installed package?

Best

Ole

**Comment by pllim** [comment]
Whoops that was my bad. Is it possible for you to use pytest ?

**Comment by pllim** [comment]
setup.py test ginga

**Comment by mitya57** [comment]
> What is the best way now to run the (non-interactive) unit test on the installed package?

I was able to run them using `pythonX.Y -c "import ginga; ginga.test()"`. However, two tests fail: `TestCmap.test_cmaps` and `TestCmap.test_get_names`. Looks like these tests do not take color maps from matplotlib into account. Is that a known issue?

**Comment by mitya57** [comment]
Also on Python 2 only, two tests fail with this error:
```
ValueError: Attempted relative import in non-package
```

for these two lines in `ginga/util/wcsmod/wcs_astlib.py`:
```python
from ..six.moves import map
from . import common
```
when calling `wcsmod.use('astlib')`. It is because `my_import` adds `wcsmod` directory into `sys.path`, so from Python point of view `wcs_astlib` is no longer a package, so `.` and `..` can not be used.

**Comment by pllim** [comment]
Thanks for the reports, @mitya57 ; I have submitted a fix at #617 . They did not get caught earlier because the current test matrix does not install `matplotlib` (also addressed in that PR) and does not test against all the supported third-party WCS packages ("future work"). It does currently test against `astropy.wcs` and there is an obvious note *not* to use relative import in that module, so in that PR, I also propagated that warning into all the other WCS modules.

**Comment by pllim** [comment]
Is this resolved? If so, feel free to close the issue. Thanks!

**Comment by olebole** [comment]
Yesss

**Comment by ejeschke** [comment]
@olebole , did this answer your question?

**Comment by ejeschke** [comment]
Nevermind, I see that the issue was closed.  Sorry.
