### ISSUE TITLE
Why Header not auto-started anymore?

### ISSUE THREAD

**Issue by pllim** [ejeschke/ginga#632]
`Header` used to auto-start when I start Ginga but not anymore. In fact, there used to be 3 tabs started on the top left area, but now only one (`Info`). Is this intentional?

```python
Bunch(module='Header', tab='Header', workspace='left', start=False,
          menu="Header [G]", hidden=False, category='Utils', ptype='global'),
```

**Comment by ejeschke** [comment]
Yes, it is intentional.  The more plugins that are auto-started, the slower the overall viewer becomes when files are loaded, as each one has a `redo()` applied.  Especially something like `Zoom` (which was one of the 3) it processes a fair bit as you mouse around the image.  The idea is that if you are not using the plugin you shouldn't have to pay the price of having it running.

I think when we progress farther along the way toward saving the state of ginga when it is closed, it could remember which plugins were running and auto start those again on startup, which will make things quite convenient.

**Comment by pllim** [comment]
Thanks for the clarification!
