### ISSUE TITLE
Feature request: Let user register custom file loader

### ISSUE THREAD

**Issue by pllim** [ejeschke/ginga#637]
While looking into #327, I need to add a file loader to read JWST ASDF file. However, that file format is so specific that I think it only makes sense to have it live within `stginga` and not here.

I see that in your WCS support machinery, you allow user to define custom WCS classes. Is it possible to extend such a feature for file formats? Please advise. Thanks!

**Comment by ejeschke** [comment]
You might want to check [this route first](https://ginga.readthedocs.io/en/latest/manual/internals.html#sec-custom-io).  I think writing your own ioloader and setting it as the class method in `AstroImage` in your boot up code for `stginga` would get you most of the way there.

Probably the one modification that would be useful in generic ginga would be to add pluggable support for registering MIME types with loaders.  Currently the code that distinguishes RGB files from FITS files is done in `Control.py` but really should probably reside in a separate class that can look at a file and based on the MIME type or other criteria suggest the proper loader class.  This would be a good test case for improving that, so that it can also handle HDF5, etc.

**Comment by ejeschke** [comment]
Not to hijack the topic, but in peeking at that documentation page, I think we need to update [this section on custom WCS](https://ginga.readthedocs.io/en/latest/manual/internals.html#sec-custom-wcs).  I think we added two new methods to the API (your work) and I extended the API to cover arrays instead of scalars.

**Comment by pllim** [comment]
> I think we added two new methods to the API (your work) 

@ejeschke , I don't think I added those. Do you mean #512?

**Comment by ejeschke** [comment]
Please see #495.  It was originally called `pointstosky()` (and `skytopoints`?) in your PR but we agreed to a name change to `datapt_to_wcspt` and `wcspt_to_datapt`.

**Comment by ejeschke** [comment]
@pllim, see PR #649 .  That will probably be helpful for writing your ASDF loader, I think.

**Comment by pllim** [comment]
Thanks, @ejeschke !
