### ISSUE TITLE
Slow response in jupyter widget interface with lots of markers

### ISSUE THREAD

**Issue by mwcraig** [ejeschke/ginga#662]
I've been playing a bit more with the Jupyter widget and notice that it gets pretty laggy (responding to pan or zoom) when there are several markeds. I think it is noticeable by 100 markers, and definitely with 1,000 markers.

I can upload a screen capture GIF if that would be helpful, and help try to trouble shoot if you can point me towards the right part of the code. 

I'm adding the markers like this:

```python
c_mark = w._ginga_viewer.add_canvas(tag='markers')
Circle = c_mark.get_draw_class('circle')

idx = 0
for loc in bad_locs:
    # Draw if not near the edges...
    if (10 < loc[0] < (img.shape[0] - 20)) and (10 < loc[1] < (img.shape[1] - 20)):
        c_mark.add(Circle(loc[1], loc[0], 30, color='cyan'))
```

**Comment by mwcraig** [comment]
That definitely speeds up addding the circles, and seems to reduce the lag some. Still noticeable, though...

**Comment by ejeschke** [comment]
This is definitely a limitation that affects any backend of Ginga.  It's due to the fact that the objects are maintained as python objects and drawn using python wrapped drawing calls.  So, for circles, an iteration of 1000 calling a python wrapper API (e.g. Qt, etc)  that draws a circle is made.  For some things, like a polygon with many points, a single drawing call is made, so something like that is faster.

I think the only way around this limitation is by eventually vectorizing the drawing.  We could maybe use cython to optomize the loops, but I'm guessing we probably need to do the looping *and* drawing in C for the best performance. 

At our observatory we've generally worked around this limitation using additional controls. For example, we have a plugin that draws circles with X's over every guide star in a DSS image, color coded by magnitude.  In a crowded field the database might reveal thousands of stars.  We prioritize them according to an algorithm and then just plot the top 100.  A slider control allows the user to "pan" across the set of stars, and we redraw the subset of stars 100 stars according to the position of the slider.  This generally works well because A) plotting even more than a hundred or so just obscures the image and B) mostly the user is just interested in the highest priority stars anyway.

**Comment by pllim** [comment]
@mwcraig mentioned https://github.com/bloomberg/bqplot/ . Perhaps Ginga can benefit from it for this issue?

**Comment by ejeschke** [comment]
Experimental aggdraw vector drawing looks promising. Drawing 10000 circles seem to work pretty fast.  Will post a reference to the PR soon.

**Comment by mwcraig** [comment]
No, closing
