### ISSUE TITLE
API for click + drag to pan?

### ISSUE THREAD

**Issue by pllim** [ejeschke/ginga#674]
My intention is to register, say, a `drag-start` callback and then let user to select a region of the image to pan to. I don't see any such functionality built-in for the standalone reference viewer (or maybe I just can't find it). Any advice on how to implement this would be greatly appreciated. Thanks!

**Comment by ejeschke** [comment]
There is a feature like that in the `Pan` plugin.  Using the right mouse button, draw a region.  It will attempt to make the channel image pan roughly to the region drawn.

The catch is that this only works really well if the region drawn has an aspect ratio similar to the channel window.  If it doesn't, it does the best it can to match the area drawn.  Anyway, if you like the functionality you (or we) could copy the relevant functionality to the `Bindings` module so it could easily be assigned using a `bindings.cfg`. You can also just monkey-patch bindings they way we were doing with @mwcraig at the SciPy sprint. 

Perhaps we could add a way to constrain the drawing to a fixed aspect ratio, in order to make it more precise.

**Comment by ejeschke** [comment]
> Using the right mouse button, draw a region. It will attempt to make the channel image pan roughly to the region drawn.

Forgot to say, draw a region *in the Pan window*.

**Comment by pllim** [comment]
Actually... Maybe I misunderstood what @eteq wants for "click-and-drag" mode. At first, I thought he wants what I mentioned above. But now that I look at it again, maybe he just wants to click to drag the window around, not to draw a region. @eteq , can you please clarify? Thanks!

**Comment by ejeschke** [comment]
> maybe he just wants to click to drag the window around

Did you get the notes from @mwcraig?  I think we implemented that feature in his jupyter notebook.  It's a one-liner.

**Comment by mwcraig** [comment]
I'll be getting around to implementing the stuff we talked about later today (or more likely tomorrow). I'll build on what @pllim has so far.

**Comment by pllim** [comment]
Looks like @mwcraig got this, so closing the issue. Sorry for the noise!
