### ISSUE TITLE
Thumbs order changes on different runs

### ISSUE THREAD

**Issue by pllim** [ejeschke/ginga#75]
For testing purposes, I have been starting Ginga with the same four images like this:
```
$ ginga image1.fits image2.fits image3.fits image4.fits
```

I notice that their ordering in `Thumbs` are not consistent between calls. Would be nice to have it ordered alphabetically or at least consistently.

**Comment by ejeschke** [comment]
@pllim, this is because Thumbs is designed to combine all images from all channels into one big wall, and it inserts them roughly in the order that the files were opened.  Since ginga offloads the file opens into separate threads (so as not to block the GUI thread), the opens may complete in an arbitrary sequence.  You can see this also if you drag a block of files from a file manager into the reference viewer window.

For our use case here at Subaru, we have lots of images coming in for quick look throughout the night, and it is intuitive that the latest ones are last in the list.

If alphabetical sorting is a desirable feature for Thumbs it seems like it would be straightforward to modify it to have an option do that.  I'll take a look at it.

**Comment by pllim** [comment]
It makes sense to order by "opened time." But when multiple files are opened at once, some kind of consistency would be desirable, but this is not a show-stopper.

**Comment by ejeschke** [comment]
Could you try commit 562c649aad8dbbe8f070356d50747a5288ec4d60 ?  In your $HOME/.ginga folder create a file called "plugin_Thumbs.cfg" .  Put in it the contents of the following:
```python
#
# Thumbs preferences file
#

# caching thumbs saves a lot of time when they need to be regenerated
cache_thumbs = True

# cache location-- "local" puts them in a .thumbs subfolder, otherwise 
# they are cached in ~/.ginga/thumbs
cache_location = 'local'

# anticipatory preloading of images shortens wait time when
# switching between thumbnails
preload_images = True

# Scroll the pane automatically when new thumbnails arrive
auto_scroll = True

# Keywords to extract and show if we mouse over the thumbnail
tt_keywords = ['OBJECT', 'FRAMEID', 'UT', 'DATE-OBS']

# How many seconds to wait after an image is altered to begin trying
# to rebuild a matching thumb.  Usually a few seconds is good in case
# there is ongoing adjustment of the image
rebuild_wait = 4.0

# Sort the thumbs alphabetically
sort_order = 'alpha'
#sort_order = None
```

You can comment out or change all options you are not interested in.  For sorting, set sort_order to "alpha".

**Comment by ejeschke** [comment]
BTW, in the current commit, the files will be sorted within channels, similar to Contents.  With a more sophisticated implementation more advanced sorting would be possible.  This is something we can improve later.

**Comment by pllim** [comment]
This works and is good enough for me. Thanks!
