### ISSUE TITLE
Feature Request: Add Lorentz function to Pick plugin

### ISSUE THREAD

**Issue by pllim** [ejeschke/ginga#754]
Someone asked me if Pick can handle Gaussian, Moffat, and Lorentz, but only first two are supported right now.

**Comment by pllim** [comment]
I am revisiting this issue and see that the functions are defined in `ginga/util/iqcalc.py`. Rather than writing up a new Lorentz function there, I wonder if I should just refactor the whole thing to use [astropy modeling](https://docs.astropy.org/en/stable/modeling/index.html).

Here is a [simple 1D fitting example](https://docs.astropy.org/en/stable/modeling/fitting.html#simple-1-d-model-fitting).

What do you think, @ejeschke ?

**Comment by ejeschke** [comment]
@pllim, I think it is a good idea to overhaul this plugin, and I think `astropy` modeling is probably the way to go. In addition, there are a couple of other things that I would like to change (or deprecate!) in the `Pick` plugin.

But we should be careful because this may be one of the most used plugins of all the ones that are distributed with the reference viewer, so I would like to make sure that everything still works as well as expected (and hopefully better!).  We are also relying on this plugin nightly at Subaru.

What do you think about an attempt to overhaul `ginga.util.iqcalc` as the first step?  Since that is used a few places, including autocuts, etc. any improvements would benefit other parts of Ginga as well.  If we kept the same API (for the moment) and make an alternative version based on astropy modelling it could be plugged in anywhere that `iqcalc` is used (we'd add Lorentz, of course).  This would allow us to directly compare the effect on `Pick` by simply assigning a different version of iqcalc inside the plugin or elsewhere.

Later we could modify it to use `photutils` or `sep` for star detection, etc. but I'd suggest just starting out by replacing the fitting parts and adding Lorentz.

**Comment by ejeschke** [comment]
@pllim, does `astropy` core have a dependency on `scipy`?  Does it have its own median filtering routine?  If so, we might be able to get rid of the Ginga use of scipy. Pretty sure the only two imports are in `iqcalc` (for the fitting) and `ginga.AutoCuts` for the `median_filter` routine.

**Comment by pllim** [comment]
AFAIK astropy fitting still farms it out to scipy.

**Comment by pllim** [comment]
A gradual switchover sounds like a good plan.
