### ISSUE TITLE
RTD is broken

### ISSUE THREAD

**Issue by pllim** [ejeschke/ginga#807]
e2b1d62f8318dc850ccf2d7c7ed5da796caa2ba6 on `master` broke RTD:
```
.../ginga/ImageView.py:docstring of ginga.ImageView.ImageViewBase.get_datarect:2:
Inline literal start-string without end-string.
```

**Comment by ejeschke** [comment]
Sorry for the churn.  I think it should be fixed now.  I have to remember to `python setup.py build_docs` to check for documentation errors in addition to the regular tests.  My bad!

**Comment by ejeschke** [comment]
@pllim, I'm missing something on the documentation build.  When I build docs locally, I get one warning about "dot" (graphviz), but otherwise the docs build is successful. On RTD, it keeps [failing](https://readthedocs.org/api/v2/build/9893199.txt).  It looks like it is still trying to import a method that is no longer visible.  Via `grep`, I cannot locate any references to the method `apply_transforms()` in the code (it was changed to _apply_transforms() and had a method signature change).

**Comment by ejeschke** [comment]
Is there some cache that can be cleaned out for RTD?

**Comment by pllim** [comment]
Yes, you can try wiping the build and then rebuild.

**Comment by pllim** [comment]
Seems fixed on `master`. Thanks!

**Comment by ejeschke** [comment]
> Yes, you can try wiping the build and then rebuild.

@pllim, I am not 100% sure this is fixed (on RTD).  How do I do the "wipe" part?  PR #805 is still failing the RTD build even though it is rebased against master.

**Comment by pllim** [comment]
RTD build on `master` seems fine today. The failure on #805 is probably real then?
