### ISSUE TITLE
Documentation on Ginga callbacks

### ISSUE THREAD

**Issue by pllim** [ejeschke/ginga#85]
In https://ginga.readthedocs.org/en/latest/manual/developers.html?highlight=callback, it mentions "plethora of callbacks" but I cannot find a list of callbacks supported by Ginga and their meanings. For example, what is the difference between `cursor-down` and `cursor-move`; which one controls dragging by left mouse button, which one by right? Are there plans to add a table of callbacks to your documentation? Thanks.

**Comment by ejeschke** [comment]
@pllim, unfortunately there is a dearth of documentation about this at the present--and it should be corrected so thank you for filing an issue.

Briefly, there are two levels at which you can register for callbacks: one level is at the "raw" event handling level and the other is at the "bindings" handling level.  Usually you want to register at the bindings level, because then you are respecting the user's opportunity to rebind these virtual events to their own key or mouse bindings, by placing a bindings.cfg file in their $HOME/.ginga folder.  Most of ginga's bindings are handled at this level.

If you look in your git clone of ginga at the [standard bindings](https://github.com/ejeschke/ginga/blob/master/examples/bindings/bindings.cfg.standard) you will see the configuration of the raw to bindings event handling.  Search for "cursor" and you will find the lines:
```python
# MOUSE/BUTTON commands
# NOTE: most plugins in the reference viewer need "none", "cursor" and "draw"
# events to work!  If you want to use them you need to provide a valid
# non-conflicting binding
ms_none = ['nobtn']
ms_cursor = ['left']
ms_wheel = []
ms_draw = ['draw+left', 'right']
```
These can be interpreted as a virtual "cursor" event is initiated by the raw "left" event (and raw "left" event is defined earlier in the file), whereas a virtual "draw" event is initiated by either a "draw mode + left" or a "right" event).  You will find that most plugins register for "cursor-down" (some button pressed), "cursor-move" (button held while moving cursor), or "cursor-up".  There is also a "draw-event" which is a callback for a draw object has been created on a canvas that has had drawing enabled for it.

**Comment by pllim** [comment]
Could you please explain what `edit-event` is for?

**Comment by ejeschke** [comment]
edit-event is an event that is generated when an object is edited on the canvas. Editing of objects is a new feature and still somewhat experimental, so I haven't documented it yet.  In particular, the UI is likely to change some.  You can try it now if you bring up the Drawing plugin.  After drawing a figure, press 'b' to enter edit mode.  You will then be able to select figures on the canvas, drag their points, etc.  While in edit mode you can draw with the right mouse button.  To exit edit mode, press Escape (escape exits any mode).

edit-event has a little different API than draw-event.  Instead of getting passed the tag of an item on the canvas, you get a reference to the object itself (that was edited).

I've changed some of the plugins to work with edit mode.  So, for example, if you have a Cuts line active, you can enter edit mode and move one of the endpoints of the cut to reposition it.

**Comment by pllim** [comment]
Thanks for the clarification. I don't really need this functionality, so it is good to know that I can ignore implementing this callback.

**Comment by ejeschke** [comment]
Closing this issue because callbacks should be documented as a part of #182.
