### ISSUE TITLE
Question about ginga.util.iqcalc.IQCalc.brightness

### ISSUE THREAD

**Issue by pllim** [ejeschke/ginga#897]
@ejeschke , can you please explain the algorithm here? Particularly, why `idx = int(len(arr2) * 0.8)`? What is so special about 0.8? I was wondering if there is an equivalent function in `photutils` for this but I cannot do it without understanding why. Hope you can clarify. Thanks!

https://github.com/ejeschke/ginga/blob/965d1ec23fdf02b7a48c86b428153346c6ce5cad/ginga/util/iqcalc.py#L451-L459

Also see: #895, #896

**Comment by ejeschke** [comment]
@pllim, it's been a long time since that code was written, and my memory is a bit hazy on it.  It looks like it is sorting all the values in the area cut out and then taking the value of the 80th percentile above the median.  I suspect that the formula came from digging through the code of `skycat` (or `ds9` or 'IRAF', maybe?), or perhaps one of our support astronomers offered it up.  I suspect it's a reasonable approximation for a more precise calculation.

If `astropy` has a good calculation for brightness above the background (inside a region) then I think you can just use it on the cutout.

**Comment by ejeschke** [comment]
The function as I understand it is a measure of the flux above the sky background. I suppose there is a good reason for not taking the maximum (peak) value in the data as the minuend.

**Comment by pllim** [comment]
Thanks for the clarification!
