### ISSUE TITLE
Histogram: Slider to control cut levels

### ISSUE THREAD

**Issue by pllim** [ejeschke/ginga#942]
Currently, the cut levels are set by manually typing in numbers into text boxes. I wonder if it would be more convenient if the limits can be set interactively. Given that `matplotlib` does not handle clicks well (unless you have a way to do that already via callbacks), maybe slider is our next best option. But interactive slider might be too sensitive limits that are too far apart but maybe not a deal breaker? This was suggested by @eteq .

![screenshot](https://ginga.readthedocs.io/en/latest/_images/histogram-plugin.png)

**Comment by ejeschke** [comment]
@pllim, I believe clicking in the plot would be the best, but of course would not be very precise, due to the compact nature of the plot, where many Y values are combined into a single X position.

Have you tried the interactive cuts feature (mode "Cuts") ?  I wonder whether you could try it and see whether it meets your needs or could be improved.  Here's how to do it: press Space, then 's'.  Press and drag the mouse in the same manner as if you were setting contrast/bias.  Only in this case, a horizontal motion sets the high cut value, and the vertical motion sets the low cut value.  It quickly becomes intuitive after a while.  The weakness of this mode currently is that it relies on getting an accurate autocuts at the beginning of the procedure (it will attempt to do an autocuts at the beginning, IIRC), so you may need to change the autocuts method in the channel to the best working choice for your data before using interactive cuts.  Also available in this mode:
* a right-click in the channel image will perform an autocuts to "restore" the cuts settings to a sort of starting state, if the cuts settings are way off;
* scrolling will increase/decrease the gap between low and high cuts; holding CTRL while scrolling will increase/decrease in much smaller increments (fine tuning)

To get out of Cuts mode, simply press ESC.

**Comment by ejeschke** [comment]
@pllim, BTW, I am not objecting to adding some more interactivity to the `Histogram` plugin...

**Comment by pllim** [comment]
> Have you tried the interactive cuts feature (mode "Cuts") ?

I did not try that before opening this issue but I did try it after you suggested above. I find it disconnected from the histogram and my mouse is set to be very sensitive, so that makes things more difficult as well.

> adding some more interactivity

I am not sure about this myself. Maybe keep this issue open for now and see if there is more demand?

**Comment by ejeschke** [comment]
@pllim, @eteq , see #945.  Seems to work well enough and is somewhat intuitive, IMO.  LMK.

We probably need to add some kind of tool tip to indicate to the user what they can do with the mouse in the plot.  I did update the plugin documentation.
