### ISSUE TITLE
TST: conda job pulling in old astropy

### ISSUE THREAD

**Issue by pllim** [ejeschke/ginga#946]
Not sure why it is not using latest released version of astropy.

`astropy-3.2.3              |   py38h516909a_0         7.2 MB  conda-forge`

As a result, I am seeing failures that are already fixed.

**Comment by mwcraig** [comment]
- First, the honest answer: I have no clue why it isn't pulling in the latest. I'd try pinning the version or putting in a minimum version and see if that is respected. My best guess is that will lead to a new error about package conflicts.

- It looks like you are not activating the conda environment which makes me wonder if that has something to do with it, but more broadly you may want to add this action: https://github.com/marketplace/actions/setup-miniconda
- Be sure to read this because you really do need to include it to get conda working: https://github.com/marketplace/actions/setup-miniconda#IMPORTANT
- I would make conda-forge the highest priority channel. One quick way to do that is to add `-c conda-forge` to all of the conda installs.
- Finally, dependency errors are much easier to understand with `mamba` than with `conda`, so if there are dependency conflicts, I'd try running with `mamba` using the setup here: https://github.com/marketplace/actions/setup-miniconda#example-6-mamba

**Comment by pllim** [comment]
> you are not activating the conda environment

I think it is running in the `base` env. 😬 

Thanks for the ideas!

**Comment by mwcraig** [comment]
> I think it is running in the base env. 😬

Maybe... at some point conda decided there was more to activating than just using the right `PATH`. I've never understood what that something more is, but in principle activating is more than just PATH.

My concern with the base environment is that there may be sort of pinning in there that ends up restricting the astropy version...

**Comment by pllim** [comment]
@mwcraig , do you have objection with #947 ?
