### ISSUE TITLE
Pick function showing different FWHM values between the FWHM figure and the Readout tab

### ISSUE THREAD

**Issue by obi-wan76** [ejeschke/ginga#969]
Sometimes when using Pick, the FWHM value at the top of the FWHM figure doesn't match the value in the Readout tab. In the attached example, the FWHM Y at the top of the figure is 7.70 px but in the Readout tab is 5.625 px. What is the difference between these two values? 

Note that that I am trying to fit a double peaked feature and it is the direction of the double peak that shows the FWHM discrepancy. 

Thanks! 
![Screen Shot 2021-08-17 at 8 10 48 PM](https://user-images.githubusercontent.com/9635910/129912670-0bd374a2-bc93-441b-b5a0-61f3b257d158.png)
![Screen Shot 2021-08-17 at 8 08 10 PM](https://user-images.githubusercontent.com/9635910/129912759-11312e65-3b0f-4efd-ace2-336a9ff3e93d.png)

**Comment by pllim** [comment]
It does seem like they are the result of two different calculations...

The one display in the plot title is from:

https://github.com/ejeschke/ginga/blob/4df2a890d85f5d11a4b19105c6c6288a669b0350/ginga/util/plots.py#L447

The one displayed in the table is from:

https://github.com/ejeschke/ginga/blob/4df2a890d85f5d11a4b19105c6c6288a669b0350/ginga/rv/plugins/Pick.py#L1719

I vaguely remember they always had shown me the same values on well-behaved objects. But in this case, it diverged. Perhaps @ejeschke can advise.

**Comment by ejeschke** [comment]
@obi-wan76, I'd have to review the code (haven't yet), but I believe this is because there are two phases to the plugin. In the first phase, all the possible candidates are selected by running a FWHM on each local approximate peak to determine eligibility according to the Settings.  Then, the top candidate is run through a second FWHM based on the center as determined by the first one.

The info in the lower widgets is populated by the first FHWM and the graph by the second.  I think the reason that a second is done is because we do not keep around all the info including cut out 1D arrays done during the first pass.  So I guess the second FWHM, getting a slightly more accurate center from the first pass, may produce a different result, especially if the center rounds to a different pixel.  In most cases, as @pllim says "for well-behaved objects" it won't matter much, but for cases as you show there can be a difference.

In any case, it should be possible to run the second pass using the same initial approximate peak rather than the center found by the first pass.  Not sure if that is a good idea or not.  Suggestions welcome!

**Comment by pllim** [comment]
It is confusing that FWHM values on plot title and report panel do not exactly mean the same thing. I can see two different solutions here:

1. Modify the plugin to sync them to the one and only correct value.
2. Clarify in tooltips and user doc that they do not mean the same thing.
