### ISSUE TITLE
Mosaic plugin in Subaru

### ISSUE THREAD

**Issue by pllim** [ejeschke/ginga#99]
In #90, you mentioned that Subaru subclassed Mosaic plugin and it is used regularly. What does the subclass has that the built-in version does not? Why is it not part of Ginga that is being distributed?

I think that it would be nice for Mosaic to list files added to mosaic (like `Contents`) and perhaps even allow user to select from that list and have display highlight the selected image in mosaic. I wonder if the Subaru subclass already has this feature.

**Comment by ejeschke** [comment]
@pllim, at Subaru we subclass this plugin to make use of some additional details about the instrument being used with the plugin.  For example, we know the exact FOV.  We also add some bits of code so that when the images arrive from the instrument to the quick look they are mosaiced into place without the user having to do anything.  There is also a nice feature to remove the overscan region from the files and to subtract flat field tiles before mosaicing.

As for your suggestion: you can currently drag images from the FBrowser plugin into Mosaic.  I suppose this could be extended into Contents or Thumbs.

**Comment by pllim** [comment]
I can definitely use the "auto mosaic" feature of your subclassed plugin. Do you mind sharing it via the same place where you grabbed my FITS image?

**Comment by pllim** [comment]
I subclassed it myself and got what I wanted.
